## Paths ##
predictions_dir: "examples/tensorflow/results/predictions"
evaluation_dir: "examples/tensorflow/results/evaluation"
data_config: "examples/tensorflow/config/data_config.yaml"

save_results: True

draw_global_plots: True
global_plots: ["test"]

## Databases ##
databases:
  - name: tf_flowers

## Evaluators ##
evaluators: 
  # - type: "tf"
  #   use_raw_data: True
  - type: "custom"
    scenarios:
      threshold: [-1, 0.3, 0.5, 0.75]

## Models ##
models_options:
  model_dir: "examples/tensorflow/results/models"
  shuffle_data: False
  augment_data: False

models:
  - name: "simple_no_augment"
    class: ".models.SimpleTFModel"
  - name: "simple_augment"
    class: ".models.SimpleTFModel"
    suffix: "_rot-{rotation}_flip-{flip}"
    scenarios: 
      rotation: [0.2, 0.3]
      flip: ["horizontal", "horizontal_and_vertical"]

