
data_config: "examples/tensorflow/config/data_config.yaml"
save_results: True

###########
## Paths ##
###########
predictions_dir: "examples/tensorflow/results/predictions"
evaluation_dir: "examples/tensorflow/results/evaluation"

###############
## Detectors ##
###############


evaluators: 
  - type: "tf"
    use_raw_data: True
  - type: "custom"

############
## Models ##
############
models_options:
  model_dir: "examples/tensorflow/results/models"
  shuffle_data: False
  augment_data: False
  reclassify: False

models:
  # - name: "CityNetTF2_Dropout"
  #   package: "dlbd.models.CityNetTF2Dropout"
  #   class: "dlbd.models.CityNetTF2Dropout.CityNetTF2Dropout"
  # - name: "CityNetOriginal"
  #   package: "dlbd.models.CityNetOriginal"
  #   class: "dlbd.models.CityNetOriginal.CityNetOriginal"
  #   version: 0
  - name: "simple_no_augment"
    class: ".models.SimpleModel"
  - name: "simple_augment"
    class: ".models.SimpleModel"

###############
## Databases ##
###############

databases:
  - name: tf_flowers