## Paths ##
data_config: "examples/tensorflow/config/data_config.yaml"
model_dir: 'examples/tensorflow/results/models'

## Databases ##
databases: ["tf_flowers"]

## Model ##
class: ".models.SimpleTFModel"
n_epochs: 20
shuffle_data: True
batch_size: 32
augment_data: True
early_stopping:
  patience: 3

## Scenarios ##
scenarios:
  - name: "simple_no_augment"
    augment_data: False
  - name: "simple_augment"
    suffix: "_rot-{rotation}_flip-{flip}"
    rotation: [0.2, 0.3]
    flip: ["horizontal", "horizontal_and_vertical"]
    augment_data: True